### PR TITLE
Fix : handle exception during create repository

### PR DESCRIPTION
**Pull request by bentshrimp**
- only first one click is available
- navigate to step1 if the repo already exists

## Describe changes

- [ ] when you create new repository, press the complete button several times
- [ ] type a new name at the step1, create a repository via GitHub as the same name, and press the complete button.

See what happens at these cases.

## Types of changes

What is the type of code change?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (changes that resolve errors)
- [ ] New feature (changes which adds functionality)
- [ ] Breaking change (big changes that affect existing functionality)
- [ ] Documentation Update

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the "README.md"
- [ ] My code follows the style guidelines of this project
- [ ] My changes generate no new warnings
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

_Please let me know if there's anything else to explain_

### CODE REVIEW

**Review by ymw0407 — CHANGES_REQUESTED** [review]
image
Good! but some exception captured....
When you enter repository (step1) through the prep button or through any path, the owner changes to the default state (your own account)! I don't think the owner should change in the situation of returning to step 1 through prev!
prev 버튼을 통해서든 어떤 경로를 통해서든 repository(step1)에 들어가게 되면, owner가 기본상태(자신의 계정)으로 변합니다! prev를 통해서 step1로 돌아가는 상황에서는 owner가 변하면 안될것 같습니다!

**Comment by ymw0407** [comment]
image

And so on Language/framework of language too...

**Comment by bentshrimp** [comment]
Oh I see. Let me deal with problem here #192

**Comment by ymw0407** [comment]
> Oh I see. Let me deal with problem here #192

OK then, I will merge this PR Thx

**Review by ymw0407 — APPROVED** [review]

**Pull request merged**
